version: "3.9"

services:
  app:
    build: .
    container_name: essence-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${postgresql://neondb_owner:npg_AJjt31oOSQLk@ep-lucky-darkness-amuwltdk-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    restart: unless-stopped